# Generated by Django 5.2.4 on 2025-08-02 03:19

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_status_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 3, 18, 5, 680945, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('lunch', 'Обед'), ('meeting', 'На встрече'), ('vacation', 'Отпуск')], default='offline', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='YmzspHPCZ88JoVbooXOkiAgaYIxxYDGod2KbwC5cQpg', max_length=64, unique=True),
        ),
    ]
