# Generated by Django 5.2.4 on 2025-08-02 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_last_status_change_invitation_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 3, 19, 33, 448269, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='WKtTjLZpgQTd2Vgxxs7j-Pckq1KmWBJVpYbNuWszHvk', max_length=64, unique=True),
        ),
    ]
