# Generated by Django 5.2.4 on 2025-08-02 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_invitation_expires_at_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 15, 15, 55, 451874, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='NN9v3S_Cm6AoiNqeMaDmS7360QWYj451K4eM5RS1wzc', max_length=64, unique=True),
        ),
    ]
