# Generated by Django 5.2.4 on 2025-08-02 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_invitation_expires_at_alter_invitation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 19, 31, 55, 728148, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.CharField(default='JxIL8ygEFjQBTkPGcMy18P8iXaXzxiQwaASYyl6Dx00', max_length=64, unique=True),
        ),
    ]
